# This workflow will build and push a new version of Ratifire to Amazon ECR.

name: S3_Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: 'eu-north-1'                    # set this to your preferred AWS region, e.g. eu-north-1
  S3_BUCKET_NAME: 'ratifire'


permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build
        run: npm install && npm run build

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --acl public-read --delete
        env:
          S3_BUCKET: ${{ env.S3_BUCKET_NAME }}